#include "GeneratorParticle.hh"
//_________________________________________________________________________________________
GeneratorParticle::GeneratorParticle() {}
//_________________________________________________________________________________________
GeneratorParticle::~GeneratorParticle() {}