/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0

/run/initialize
/output/filename gun_electron_mono.root

# general, marley
/generator/set general

# e-, e+, mu-, mu+, neutron, proton, anti_proton, pi-, pi+, pi0, kaon-, kaon+, gamma, opticalphoton, ...
/gps/particle mu-

# point source
/gps/pos/type Point
/gps/pos/centre 0 0 0 cm

# angular distribution
/gps/ang/type iso

# energy distribution
/gps/ene/type Mono
/gps/ene/mono 10 MeV

# run
/run/beamOn 1000